import {
  SiExpress,
  SiMongodb,
  SiNodedotjs,
  SiWordpress,
  SiZod,
  SiJest,
  SiStrapi,
  SiPhp,
  SiMysql,
  SiGraphql,
  SiRedux,
  SiTailwindcss,
  SiTypescript,
  SiNextdotjs,
  SiBootstrap,
} from "react-icons/si";
import { DiHtml5, DiCss3, DiJsBadge, DiReact } from "react-icons/di";
import Image from "next/image";
import { FaFacebook, FaLinkedin, FaGithub } from "react-icons/fa";
import { PlaywrightSVG } from "./components/svg";

export const links = [
  {
    src: "https://www.facebook.com/profile.php?id=100043988671187",
    icon: <FaFacebook color="#01f3f4" />,
    lable: "Facebook",
  },
  {
    src: "https://www.linkedin.com/in/med0-hassan/",
    icon: <FaLinkedin color="#01f3f4" />,
    lable: "Linkedin",
  },
  {
    src: "https://github.com/2MohamedHssan",
    icon: <FaGithub color="#01f3f4" />,
    lable: "Github",
  },
];

export const allCertifications = [
  {
    id: 1,
    dataAnimation: "fade-down",
    src: "/web.jpg",
    alt: "Web Design Certification",
    title: "Web Design",
  },
  {
    id: 2,
    dataAnimation: "fade-down",
    src: "/photoshop.jpg",
    alt: "Adobe Photoshop Certification",
    title: "Adobe Photoshop",
  },
  {
    id: 3,
    dataAnimation: "fade-up",
    src: "/IT.jpg",
    alt: "IT Support Certification",
    title: "IT Support",
  },
  {
    id: 4,
    dataAnimation: "fade-down",
    src: "/mohamedFullstak.png",
    alt: "Full Stack Development Certification",
    title: "Full Stack Development Internship",
  },
  {
    id: 5,
    dataAnimation: "fade-down",
    src: "/React Essential Training.png",
    alt: "React Essential Training Certification",
    title: "React Essential Training",
  },
  {
    id: 6,
    dataAnimation: "fade-down",
    src: "/React_Design_patterns.png",
    alt: "React Design patterns",
    title: "React Design patterns",
  },
];

export const skills = [
  {
    icon: <DiHtml5 size={40} className="text-[#e34c26]" />,
    title: "HTML5",
    curent: true,
    description: "Semantic structure and accessibility.",
  },
  {
    icon: <SiJest size={40} className="text-[#e35b64]" />,
    title: "Jest",
    curent: true,
    description: "Unit testing framework for JavaScript.",
  },
  {
    icon: <PlaywrightSVG size={40} />,
    title: "Playwright",
    curent: true,
    description: "Unit testing framework for JavaScript.",
  },
  {
    icon: <SiZod size={40} className="text-[#3B82F6]" />,
    title: "Zod",
    curent: true,
    description: "Schema validation for TypeScript.",
  },
  {
    icon: <SiStrapi size={40} className="text-[#8e75ff]" />,
    title: "Strapi",
    curent: true,
    description: "Headless CMS for custom APIs.",
  },
  {
    icon: <FaGithub size={40} className="text-[#000]" />,
    title: "GitHub",
    curent:true,
    description: "Version control and collaboration.",
  },
  {
    icon: <DiCss3 size={40} className="text-[#1572b6]" />,
    title: "CSS3",
    curent: true,
    description: "Responsive styling and animations.",
  },
  {
    icon: <SiWordpress size={40} className="text-[#1572b6]" />,
    title: "WordPress",
    curent: false,
    description: "Flexible CMS for custom sites.",
  },

  {
    icon: <SiRedux size={40} className="text-[#764ABC]" />,
    title: "Redux",
    curent: true,
    description: "Predictable state container for JS apps.",
  },
  {
    icon: <DiJsBadge size={40} className="text-[#f7df1e]" />,
    title: "JavaScript",
    curent: false,
    description: "Core scripting language for the web.",
  },
  {
    icon: <SiPhp size={40} className="text-[#4F5D95]" />,
    title: "PHP",
    curent: false,
    description: "Backend scripting for dynamic sites.",
  },
  {
    icon: <DiReact size={40} className="text-[#61dbfb]" />,
    title: "React",
    curent: true,
    description: "Modern component-based UI development.",
  },
  {
    icon: <SiMysql size={40} className="text-[#00758F]" />,
    title: "MySQL",
    curent: false,
    description: "Structured database management.",
  },
  {
    icon: <SiNextdotjs size={40} className="text-[#000]" />,
    title: "Next.js",
    curent: true,
    description: "React framework for SSR & routing.",
  },
  {
    icon: <SiTypescript size={40} className="text-[#3178C6]" />,
    title: "TypeScript",
    curent: true,
    description: "Typed superset of JavaScript.",
  },
  {
    icon: <SiGraphql size={40} className="text-[#E10098]" />,
    title: "GraphQL",
    curent: false,
    description: "Query language for flexible APIs.",
  },
  {
    icon: <SiTailwindcss size={40} className="text-[#38B2AC]" />,
    title: "Tailwind CSS",
    curent: true,
    description: "Utility-first framework for fast styling.",
  },
  {
    icon: <Image src="/logo.svg" alt="Vite" width={40} height={40} />,
    title: "Vite",
    curent: true,
    description: "Fast build tool for modern frontends.",
  },
  {
    icon: <SiBootstrap size={40} className="text-[#7952B3]" />,
    title: "Bootstrap",
    curent: false,
    description: "Quick responsive design components.",
  },
  {
    icon: <SiNodedotjs size={40} className="text-[#339933]" />,
    title: "Node.js",
    curent: true,
    description: "JavaScript runtime for servers.",
  },
  {
    icon: <SiExpress size={40} className="text-white" />,
    title: "Express.js",
    curent: false,
    description: "Minimalist backend framework.",
  },
  {
    icon: <SiMongodb size={40} className="text-[#4DB33D]" />,
    title: "MongoDB",
    curent: false,
    description: "NoSQL database for scalable apps.",
  },
];

export const projects = [
  {
    url: "https://techyardhub.com/",
    tools: ["React.js", "Tailwind"],
    imgsrc: "/Tech.png",
    pname: "TECH YARD HUB ",
    category: "Reactjs",
  },
  {
    url: "https://byload-uae.com/",
    tools: ["React.js", "Tailwind"],
    imgsrc: "/Byload.png",
    pname: "Bylaod ",
    category: "Reactjs",
  },
  {
    url: "#",
    tools: ["React.js", "Tailwind"],
    imgsrc: "/dashbordTech.png",
    pname: "Dashbord ",
    category: "Reactjs",
  },
  {
    url: "https://dfm-analyzer.vercel.app/",
    tools: ["React.js", "Tailwind"],
    imgsrc: "/DFM.png",
    pname: "DFM Analyzer ",
    category: "Reactjs",
  },
  {
    url: "https://2mohamedhssan.github.io/EliteCorp/",
    imgsrc: "/Eipct1.png",
    pname: "EliteCorp",
    tools: ["HTML5", "TailwindCss", "JavaScript"],
    category: "JavaScript",
  },
  {
    url: "https://2mohamedhssan.github.io/Bondi/",
    imgsrc: "/bondi.png",
    tools: ["HTML5", "CSS3"],
    pname: "Bondi",
    category: "HTML&CSS",
  },
  {
    url: "https://2mohamedhssan.github.io/First-JsDesign/",
    imgsrc: "/swaping.png",
    tools: ["HTML5", "CSS3", "JavaScript"],
    pname: "JsDesign",
    category: "JavaScript",
  },
  {
    url: "https://2mohamedhssan.github.io/Dashboard-Design/index.html",
    tools: ["HTML5", "CSS3"],
    imgsrc: "/dashbord.png",
    pname: "Dashboard",
    category: "HTML&CSS",
  },
  {
    url: "https://github.com/2MohamedHssan/Next-app",
    tools: ["TailwindCss", "Next.js"],
    imgsrc: "/tow.jpg",
    pname: "Next-app",
    category: "Nextjs",
  },
  {
    url: "https://2mohamedhssan.github.io/Clipboard/",
    imgsrc: "/clipbord.png",
    tools: ["HTML5", "TailwindCss"],
    pname: "Clipboard",
    category: "HTML&CSS",
  },
  {
    url: "https://2mohamedhssan.github.io/Kasper-Design/",
    imgsrc: "/kasper.png",
    tools: ["HTML5", "CSS3"],
    pname: "Kasper",
    category: "HTML&CSS",
  },
  {
    url: "https://2mohamedhssan.github.io/First-Software-design/",
    tools: ["HTML5", "CSS3"],
    imgsrc: "/profirst.png",
    pname: "Company-portfolio",
    category: "HTML&CSS",
  },
  {
    url: "https://2mohamedhssan.github.io/Awesome-Design/",
    tools: ["HTML5", "CSS3"],
    imgsrc: "/tempthree.png",
    pname: "Design",
    category: "HTML&CSS",
  },
  {
    url: "https://telmeez-platform.vercel.app/",
    tools: ["Next.js", "Tailwind"],
    imgsrc: "/telmeez.png",
    pname: "Telmeez",
    category: "Nextjs",
  },
  {
    url: "https://portfolio-v418.vercel.app/",
    tools: ["Next.js", "Tailwind"],
    imgsrc: "/newportoflio.png",
    pname: "myPortoflio",
    category: "Nextjs",
  },
  {
    url: "https://github.com/2MohamedHssan/DepoTask",
    tools: ["React.js", "Tailwind"],
    imgsrc: "/one.jpg",
    pname: "DepoTask",
    category: "Reactjs",
  },
  {
    url: "https://github.com/2MohamedHssan/Courses-front",
    tools: ["React.js", "Tailwind"],
    imgsrc: "/four.jpg",
    pname: "Courses-front",
    category: "Reactjs",
  },
  {
    url: "https://github.com/2MohamedHssan/Image-Gallery-app",
    tools: ["React.js", "Tailwind"],
    imgsrc: "/six.jpg",
    pname: "Image-Gallery-app",
    category: "Reactjs",
  },
  {
    url: "https://2mohamedhssan.github.io/Memory-Game/",
    tools: ["HTML5", "CSS3", "JavaScript"],
    imgsrc: "/Memory.png",
    pname: "Memory-Game",
    category: "Games",
  },
  {
    url: "https://2mohamedhssan.github.io/Hangman-Game/",
    tools: ["HTML5", "CSS3", "JavaScript"],
    imgsrc: "/Hangman.png",
    pname: "Hangman-Game",
    category: "Games",
  },
  {
    url: "https://2mohamedhssan.github.io/TypingRace-Game/",
    tools: ["HTML5", "CSS3", "JavaScript"],
    imgsrc: "/typing.png",
    pname: "TypingRace-Game",
    category: "Games",
  },
  {
    url: "https://2mohamedhssan.github.io/Question-Game/",
    tools: ["HTML5", "CSS3", "JavaScript"],
    imgsrc: "/Qustion.png",
    pname: "Qustion-Game",
    category: "Games",
  },
];
